import { Report, UtilizationData } from '@/types';

export const DUMMY_REPORT: Report = {
  id: 'rep-init-001',
  file_name: 'MW link Tracker Bali Nusra.xlsx',
  uploaded_at: new Date('2026-09-08T08:30:00Z').toISOString(),
  report_period: 'W34',
  total_rows: 36,
  processed_rows: 36,
};

export const DUMMY_UTILIZATION_DATA: UtilizationData[] = [
  // --- BALI (8 links) ---
  {
    id: 'link-bali-01',
    report_id: 'rep-init-001',
    link_id: '19DPS0021',
    ref_link_id: '19DPS0021-19DPS0014',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-DENPASAR UTARA',
    site_name: 'DPS_GATSU_BARAT',
    transport_type: 'MW-HWI',
    util_avg: 88.45,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 88.45, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-bali-02',
    report_id: 'rep-init-001',
    link_id: '19BDG0045',
    ref_link_id: '19BDG0045-19BDG0010',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-BADUNG KUTA',
    site_name: 'KUTA_SUNSET_ROAD',
    transport_type: 'Direct',
    util_avg: 82.10,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 82.10, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-bali-03',
    report_id: 'rep-init-001',
    link_id: '19GYR0012',
    ref_link_id: '19GYR0012-19DPS0005',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-GIANYAR UBUD',
    site_name: 'UBUD_MONKEY_FOREST',
    transport_type: 'MW-HWI',
    util_avg: 74.30,
    status: 'Warning',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 74.30, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-bali-04',
    report_id: 'rep-init-001',
    link_id: '19TBN0033',
    ref_link_id: '19TBN0033-19TBN0002',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-TABANAN KOTA',
    site_name: 'TABANAN_KOTA_HUB',
    transport_type: 'Direct',
    util_avg: 54.12,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 54.12, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-bali-05',
    report_id: 'rep-init-001',
    link_id: '19SNG0018',
    ref_link_id: '19SNG0018-19SNG0001',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-SINGARAJA',
    site_name: 'BULELENG_PANTAI',
    transport_type: 'MW-HWI',
    util_avg: 42.50,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 42.50, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-bali-06',
    report_id: 'rep-init-001',
    link_id: '19JBR0008',
    ref_link_id: '19JBR0008-19JBR0002',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-NEGARA',
    site_name: 'NEGARA_GILIMANUK',
    transport_type: 'MW-HWI',
    util_avg: 38.90,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 38.90, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-bali-07',
    report_id: 'rep-init-001',
    link_id: '19KLK0015',
    ref_link_id: '19KLK0015-19DPS0010',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-NUSA PENIDA',
    site_name: 'NUSA_LEMBONGAN_HUB',
    transport_type: 'MW-HWI',
    util_avg: 81.70,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 81.70, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-bali-08',
    report_id: 'rep-init-001',
    link_id: '19KRA0022',
    ref_link_id: '19KRA0022-19KRA0005',
    region: 'BALI NUSRA',
    province: 'BALI',
    micro_cluster: 'MC-KARANGASEM',
    site_name: 'PADANG_BAI_FERRY',
    transport_type: 'Direct',
    util_avg: 61.40,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 61.40, utilization_level: 'Medium' },
    ],
  },

  // --- NTB (8 links) ---
  {
    id: 'link-ntb-01',
    report_id: 'rep-init-001',
    link_id: '19MTR0055',
    ref_link_id: '19MTR0055-19MTR0012',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-MATARAM BARAT',
    site_name: 'MATARAM_AMPENAN',
    transport_type: 'MW-HWI',
    util_avg: 89.15,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 89.15, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntb-02',
    report_id: 'rep-init-001',
    link_id: '19LOB0034',
    ref_link_id: '19LOB0034-19MTR0008',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-LOMBOK BARAT',
    site_name: 'SENGGIGI_RESORT',
    transport_type: 'Direct',
    util_avg: 84.80,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 84.80, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntb-03',
    report_id: 'rep-init-001',
    link_id: '19LOT0042',
    ref_link_id: '19LOT0042-19LOT0010',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-LOMBOK TIMUR',
    site_name: 'SELONG_KOTA',
    transport_type: 'MW-HWI',
    util_avg: 76.50,
    status: 'Warning',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 76.50, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-ntb-04',
    report_id: 'rep-init-001',
    link_id: '19SBW0019',
    ref_link_id: '19SBW0019-19SBW0005',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-SUMBAWA BESAR',
    site_name: 'SUMBAWA_PUSAT',
    transport_type: 'MW-HWI',
    util_avg: 59.20,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 59.20, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-ntb-05',
    report_id: 'rep-init-001',
    link_id: '19BIM0027',
    ref_link_id: '19BIM0027-19BIM0003',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-BIMA KOTA',
    site_name: 'BIMA_RABA_HUB',
    transport_type: 'Direct',
    util_avg: 81.30,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 81.30, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntb-06',
    report_id: 'rep-init-001',
    link_id: '19DMP0011',
    ref_link_id: '19DMP0011-19BIM0005',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-DOMPU',
    site_name: 'DOMPU_KOTA',
    transport_type: 'MW-HWI',
    util_avg: 49.80,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 49.80, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-ntb-07',
    report_id: 'rep-init-001',
    link_id: '19LOT0088',
    ref_link_id: '19LOT0088-19LOT0012',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-LOMBOK UTARA',
    site_name: 'GILI_TRAWANGAN_MW',
    transport_type: 'MW-HWI',
    util_avg: 86.40,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 86.40, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntb-08',
    report_id: 'rep-init-001',
    link_id: '19LOB0076',
    ref_link_id: '19LOB0076-19MTR0020',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA BARAT',
    micro_cluster: 'MC-LOMBOK TENGAH',
    site_name: 'MANDALIKA_CIRCUIT',
    transport_type: 'Direct',
    util_avg: 68.20,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 68.20, utilization_level: 'Medium' },
    ],
  },

  // --- NTT (10 links - matching real Excel structure) ---
  {
    id: 'link-ntt-01',
    report_id: 'rep-init-001',
    link_id: '19KAI0028',
    ref_link_id: '19KAI0025-19KAI0028',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-FLORES TIMUR',
    site_name: 'PAILELANG_CM',
    transport_type: 'MW-HWI',
    util_avg: 80.09,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 80.09, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntt-02',
    report_id: 'rep-init-001',
    link_id: '19KAI0029',
    ref_link_id: '19KAI0029-19KAI0031',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-FLORES TIMUR',
    site_name: 'ALIMMEBUNG',
    transport_type: 'MW-HWI',
    util_avg: 49.24,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 49.24, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-ntt-03',
    report_id: 'rep-init-001',
    link_id: '19KAI0026',
    ref_link_id: '19KAI0026-19KAI0027',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-FLORES TIMUR',
    site_name: 'MOTONGBANG_TB',
    transport_type: 'MW-HWI',
    util_avg: 48.84,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 48.84, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-ntt-04',
    report_id: 'rep-init-001',
    link_id: '19KPG0011',
    ref_link_id: '19KPG0011-19KPG0001',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-KUPANG KOTA',
    site_name: 'KUPANG_OEBOBO',
    transport_type: 'Direct',
    util_avg: 87.60,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 87.60, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntt-05',
    report_id: 'rep-init-001',
    link_id: '19KAI0030',
    ref_link_id: '19KAI0025-19KAI0030',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-FLORES TIMUR',
    site_name: 'LEWOLEBA_HUB',
    transport_type: 'MW-HWI',
    util_avg: 55.35,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 55.35, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-ntt-06',
    report_id: 'rep-init-001',
    link_id: '19ENDE0015',
    ref_link_id: '19ENDE0015-19ENDE0002',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-ENDE',
    site_name: 'ENDE_PELABUHAN',
    transport_type: 'MW-HWI',
    util_avg: 83.20,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 83.20, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntt-07',
    report_id: 'rep-init-001',
    link_id: '19MGR0022',
    ref_link_id: '19MGR0022-19MGR0004',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-LABUAN BAJO',
    site_name: 'LABUAN_BAJO_AIRPORT',
    transport_type: 'Direct',
    util_avg: 89.90,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'Critical-2' },
      { week: 'W34', utilization_value: 89.90, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-ntt-08',
    report_id: 'rep-init-001',
    link_id: '19SKK0014',
    ref_link_id: '19SKK0014-19SKK0001',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-MAUMERE',
    site_name: 'MAUMERE_KOTA',
    transport_type: 'MW-HWI',
    util_avg: 71.50,
    status: 'Warning',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 71.50, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-ntt-09',
    report_id: 'rep-init-001',
    link_id: '19SMB0009',
    ref_link_id: '19SMB0009-19SMB0001',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-SUMBA TIMUR',
    site_name: 'WAINGAPU_CENTRAL',
    transport_type: 'MW-HWI',
    util_avg: 64.20,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 64.20, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-ntt-10',
    report_id: 'rep-init-001',
    link_id: '19ROT0005',
    ref_link_id: '19ROT0005-19KPG0008',
    region: 'BALI NUSRA',
    province: 'NUSA TENGGARA TIMUR',
    micro_cluster: 'MC-ROTE NDAO',
    site_name: 'BAA_ROTE_ISLAND',
    transport_type: 'Direct',
    util_avg: null, // Categorical only test case
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: null, utilization_level: 'High' },
    ],
  },

  // --- JAWA TIMUR (10 links) ---
  {
    id: 'link-jatim-01',
    report_id: 'rep-init-001',
    link_id: '19SBY0102',
    ref_link_id: '19SBY0102-19SBY0050',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-SURABAYA PUSAT',
    site_name: 'SBY_TUNJUNGAN_PLAZA',
    transport_type: 'Direct',
    util_avg: 91.20,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'Critical-2' },
      { week: 'W34', utilization_value: 91.20, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-jatim-02',
    report_id: 'rep-init-001',
    link_id: '19MLG0045',
    ref_link_id: '19MLG0045-19MLG0011',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-MALANG KOTA',
    site_name: 'MALANG_IJEN_BOULEVARD',
    transport_type: 'MW-HWI',
    util_avg: 83.70,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 83.70, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-jatim-03',
    report_id: 'rep-init-001',
    link_id: '19SDA0038',
    ref_link_id: '19SDA0038-19SBY0020',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-SIDOARJO UTARA',
    site_name: 'WARU_SIDOARJO_HUB',
    transport_type: 'Direct',
    util_avg: 85.60,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'High' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 85.60, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-jatim-04',
    report_id: 'rep-init-001',
    link_id: '19GSK0019',
    ref_link_id: '19GSK0019-19SBY0015',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-GRESIK KOTA',
    site_name: 'GRESIK_PORT_HUB',
    transport_type: 'MW-HWI',
    util_avg: 73.40,
    status: 'Warning',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W34', utilization_value: 73.40, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-jatim-05',
    report_id: 'rep-init-001',
    link_id: '19KDR0022',
    ref_link_id: '19KDR0022-19KDR0005',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-KEDIRI KOTA',
    site_name: 'KEDIRI_DOHO',
    transport_type: 'MW-HWI',
    util_avg: 58.70,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 58.70, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-jatim-06',
    report_id: 'rep-init-001',
    link_id: '19JBR0067',
    ref_link_id: '19JBR0067-19JBR0002',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-JEMBER KOTA',
    site_name: 'JEMBER_ALUN_ALUN',
    transport_type: 'Direct',
    util_avg: 64.90,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 64.90, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-jatim-07',
    report_id: 'rep-init-001',
    link_id: '19BYW0031',
    ref_link_id: '19BYW0031-19BYW0004',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-BANYUWANGI',
    site_name: 'KETAPANG_PORT',
    transport_type: 'MW-HWI',
    util_avg: 82.50,
    status: 'High',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'High' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 82.50, utilization_level: 'High' },
    ],
  },
  {
    id: 'link-jatim-08',
    report_id: 'rep-init-001',
    link_id: '19MDN0014',
    ref_link_id: '19MDN0014-19MDN0001',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-MADIUN',
    site_name: 'MADIUN_KOTA_HUB',
    transport_type: 'Direct',
    util_avg: 52.30,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 52.30, utilization_level: 'Low' },
    ],
  },
  {
    id: 'link-jatim-09',
    report_id: 'rep-init-001',
    link_id: '19MDR0051',
    ref_link_id: '19MDR0051-19SBY0030',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-MADURA BANGKALAN',
    site_name: 'SURAMADU_NORTH',
    transport_type: 'MW-HWI',
    util_avg: 78.10,
    status: 'Warning',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W32', utilization_value: null, utilization_level: 'Medium' },
      { week: 'W33', utilization_value: null, utilization_level: 'High' },
      { week: 'W34', utilization_value: 78.10, utilization_level: 'Medium' },
    ],
  },
  {
    id: 'link-jatim-10',
    report_id: 'rep-init-001',
    link_id: '19PAS0018',
    ref_link_id: '19PAS0018-19SDA0010',
    region: 'JAWA TIMUR',
    province: 'JAWA TIMUR',
    micro_cluster: 'MC-PASURUAN',
    site_name: 'PASURUAN_INDUSTRI',
    transport_type: 'MW-HWI',
    util_avg: 61.80,
    status: 'Normal',
    created_at: new Date('2026-09-08T08:30:00Z').toISOString(),
    weekly_history: [
      { week: 'W31', utilization_value: null, utilization_level: 'Low' },
      { week: 'W32', utilization_value: null, utilization_level: 'Low' },
      { week: 'W33', utilization_value: null, utilization_level: 'Low' },
      { week: 'W34', utilization_value: 61.80, utilization_level: 'Low' },
    ],
  },
];
